FROM node:14

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG DEFAULT_PORT=80

ENV PORT $DEFAULT_PORT

# $ indicates env variable
EXPOSE $PORT

# anonymous volumes
# VOLUME ["/app/feedback"]

# CMD ["node", "server.js"]

# using nodemon
CMD ["npm", "start"]